# Generated by Django 6.1 on 2026-08-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Terminee'), ('FAILED', 'Echouee')], db_index=True, default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analyse de CV',
                'verbose_name_plural': 'analyses de CV',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cv_analyzer_status_9baae6_idx'), models.Index(fields=['user', '-created_at'], name='cv_analyzer_user_id_77b50d_idx')],
            },
        ),
    ]
